[package]
edition = "2021"
name    = "warren-abstract-machine"
version = "0.1.0"

[dependencies]
anyhow      = "1.0.86"
derive_more = { version = "1.0.0", features = ["full"] }
indoc       = "2.0.5"
itertools   = "0.13.0"
logos       = "0.14.0"
regex       = "1.11.1"
velcro      = "0.5.4"
